// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOStFBNgSP1aofZnQ3dUP2UMPvqZjq9k',
    appId: '1:277286612451:web:82e75c8416ad6f1a4a84d6',
    messagingSenderId: '277286612451',
    projectId: 'device-streaming-36a29ebc',
    authDomain: 'device-streaming-36a29ebc.firebaseapp.com',
    storageBucket: 'device-streaming-36a29ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2Zy889lgv8CTdD4xxN-cdW1FU5wpOzo',
    appId: '1:277286612451:android:f75345d42fe2801f4a84d6',
    messagingSenderId: '277286612451',
    projectId: 'device-streaming-36a29ebc',
    storageBucket: 'device-streaming-36a29ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELomK-fCt0fb4oR6HVODGRjmZNucnBvY',
    appId: '1:277286612451:ios:3c458142ec3d02744a84d6',
    messagingSenderId: '277286612451',
    projectId: 'device-streaming-36a29ebc',
    storageBucket: 'device-streaming-36a29ebc.firebasestorage.app',
    iosBundleId: 'com.example.userListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDELomK-fCt0fb4oR6HVODGRjmZNucnBvY',
    appId: '1:277286612451:ios:3c458142ec3d02744a84d6',
    messagingSenderId: '277286612451',
    projectId: 'device-streaming-36a29ebc',
    storageBucket: 'device-streaming-36a29ebc.firebasestorage.app',
    iosBundleId: 'com.example.userListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOStFBNgSP1aofZnQ3dUP2UMPvqZjq9k',
    appId: '1:277286612451:web:e58a7d14c56bf1f24a84d6',
    messagingSenderId: '277286612451',
    projectId: 'device-streaming-36a29ebc',
    authDomain: 'device-streaming-36a29ebc.firebaseapp.com',
    storageBucket: 'device-streaming-36a29ebc.firebasestorage.app',
  );
}
